name: "Build documentation"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-build
        path: site
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: site
